# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - MAINTAINERS.md
      - LICENSE
      - NOTICE
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: xmidt-org/.github/.github/workflows/go-ci.yml@0e86f380809385408ec167ed731a2d44bbe8c6aa
    secrets: inherit
